---
output:
  pdf_document: default
  word_document: default
  html_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# DLfuse: Distributed Lag Data Fusion for Estimating Ambient Air Pollution

## DLfuseST_Example

[1] Simulate data from the proposed model:

* Setting the reproducibility seed and initializing packages for data simulation: 
```{r}
set.seed(3146)

library(DLfuse)
library(geoR)  #Spatial covariance functions
library(mnormt)  #Multivariate normal distribution
library(matrixStats)  #colMedians
```

* Setting the global data values:
```{r}
##########################################
#Full CMAQ Grid
##########################################
m<-(5^2)
grid<-matrix(0, 
             nrow = m, 
             ncol = 2)
counter<-1
for(j in 1:sqrt(m)){
   for(k in 1:sqrt(m)){

      grid[counter,]<-c(j,k)
      counter<-counter + 
               1

      }
   }

neighbors<-1/as.matrix(dist(grid,
                            diag = TRUE, 
                            upper = TRUE))
diag(neighbors)<-0

CAR<-diag(rowSums(neighbors)) - 
     neighbors

##################################################################
#Full AQS Locations
##################################################################
sample_size<-list(0)
CMAQ_key<-list(0)
AQS_key<-list(0)

sample_size[[1]]<-rpois(n = m,
                        lambda = 1)
sample_size[[1]]<-pmax(sample_size[[1]], 
                       rep(1, 
                           times = m))

locs<-matrix(runif(n = (2*sum(sample_size[[1]])),
                   min = 0,
                   max = 1),
             ncol = 2)
spatial_dists<-as.matrix(dist(locs,
                              diag = TRUE,
                              upper = TRUE))
diag(spatial_dists)<-0

CMAQ_key[[1]]<-rep(0, 
                   times = sum(sample_size[[1]]))
counter<-0
for(j in 1:length(sample_size[[1]])){

   CMAQ_key[[1]][(1 + counter):(sample_size[[1]][j] + counter)]<-j
   counter<-counter + 
            sample_size[[1]][j]

   }

CMAQ_key[[1]]<-c(1:nrow(neighbors))
AQS_key[[1]]<-c(1:nrow(spatial_dists))

####################################################################
#Creating the Spatiotemporal Information
####################################################################
d<-16  #Must be larger than one
if(d > 1){
  for(j in 2:d){

     CMAQ_key[[j]]<-sample(c(1:m), 
                           size = round((4/5)*m),
                           replace = FALSE)

     sample_size[[j]]<-rpois(n = length(CMAQ_key[[j]]),
                             lambda = 1)
     sample_size[[j]]<-pmax(sample_size[[j]], 
                            rep(1, 
                                times=length(CMAQ_key[[j]])))

     while(sum(sample_size[[j]]) > nrow(spatial_dists)){

          sample_size[[j]]<-rpois(n = length(CMAQ_key[[j]]),
                                  lambda = 1)
          sample_size[[j]]<-pmax(sample_size[[j]], 
                                 rep(1, 
                                     times = length(CMAQ_key[[j]])))

          }

     AQS_key[[j]]<-sample(c(1:nrow(spatial_dists)),
                          size = sum(sample_size[[j]]),
                          replace = FALSE)

     }
  }

#############################################################################
#True Spatial Parameter Settings
#############################################################################
sigma2_epsilon_true<-0.05

beta0_true<-0.25
beta1_true<-1.75

A11_true<-0.05
A22_true<-0.05
A21_true<- -0.01

phi0_true<-1.50
Sigma0_true<-cov.spatial(spatial_dists,
                         cov.model = "exponential",
                         cov.pars=c(1, (1/phi0_true)))
w0_true<-rmnorm(n = 1,
                mean = rep(0, 
                           times = sum(sample_size[[1]])),
                varcov = Sigma0_true)
w0_true<-w0_true - 
         mean(w0_true)
beta0_tilde_true<-A11_true*w0_true

phi1_true<-1.50
Sigma1_true<-cov.spatial(spatial_dists,
                         cov.model = "exponential",
                         cov.pars = c(1, (1/phi1_true)))
w1_true<-rmnorm(n = 1,
                mean = rep(0, 
                           times=sum(sample_size[[1]])),
                varcov = Sigma1_true)
w1_true<-w1_true - 
         mean(w1_true)
beta1_tilde_true<-A21_true*w0_true +
                  A22_true*w1_true

tau2_true<-1.00
rho_true<-0.99  #ICAR Model Approximation
CAR_cov_true<-tau2_true*chol2inv(chol(rho_true*CAR + (1 - rho_true)*diag(m)))
alpha_true<-rmnorm(n = 1,
                   mean = rep(0, 
                              times=m),
                   varcov = CAR_cov_true)
alpha_true<-alpha_true - 
            mean(alpha_true)

mu_true<-1.00

####################################################
#True Temporal Parameters
####################################################
V_true<-matrix(c(0.03, -0.01, -0.01, 0.03), 
               nrow = 2, 
               ncol = 2)

rho1_true<-0.90
rho2_true<-0.10
Omega_true<-matrix(0, 
                   nrow = 2, 
                   ncol = 2)
Omega_true[1,1]<-rho1_true
Omega_true[2,2]<-rho2_true

betat_true<-matrix(0, 
                   nrow = d, 
                   ncol = 2)
betat_true[1,]<-rmnorm(n = 1, 
                       mean = rep(0, 
                                  times = 2), 
                       varcov = V_true)

rho3_true<-0.75

sigma2_delta_true<-0.01

mut_true<-rep(0, 
              times = d)
mut_true[1]<-rnorm(n = 1,
                   mean = 0,
                   sd = sqrt(sigma2_delta_true))

for(j in 2:d){

   betat_true[j,]<-Omega_true%*%betat_true[(j-1),] + 
                   rmnorm(n = 1, 
                          mean = rep(0, 
                                     times = 2), 
                          varcov = V_true)

   mut_true[j]<-rho3_true*mut_true[j-1] +
                rnorm(n = 1, 
                      mean = 0, 
                      sd = sqrt(sigma2_delta_true))

   }

betat_true[,1]<-betat_true[,1] -
                mean(betat_true[,1])
betat_true[,2]<-betat_true[,2] -
                mean(betat_true[,2])

mut_true<-mut_true - 
          mean(mut_true)

###########################################################################
#Creating Lagged Covariates and Observed Data
###########################################################################
L<-11
y<-list(0)
z<-list(0)
covars_true<-list(0)
for(j in 1:d){

   z[[j]]<-matrix(rgamma(n = (length(CMAQ_key[[j]])*L), 
                         shape = 1, 
                         rate = 1), 
                  nrow = length(CMAQ_key[[j]]), 
                  ncol = L)

   covars_true[[j]]<-construct_lagged_covars_st(z[[j]],
                                                mu_true,
                                                mut_true[j],
                                                alpha_true,
                                                sample_size[[j]],
                                                CMAQ_key[[j]])[[1]]

   y[[j]]<-rnorm(n = sum(sample_size[[j]]),
                 mean = ((beta0_true + betat_true[j,1] + 
                          beta0_tilde_true[AQS_key[[j]]]) + 
                        (beta1_true + betat_true[j,2] + 
                         beta1_tilde_true[AQS_key[[j]]])*covars_true[[j]]),
                 sd = sqrt(sigma2_epsilon_true))

   }

sample_size_validation<-sample_size[[d]]
AQS_key_validation<-AQS_key[[d]]
CMAQ_key_validation<-CMAQ_key[[d]]
y_validation<-y[[d]]
z_validation<-z[[d]]

sample_size[[d]]<-NULL
AQS_key[[d]]<-NULL
CMAQ_key[[d]]<-NULL
y[[d]]<-NULL
z[[d]]<-NULL
```

[2] Fit DLfuse to a subset of the data:

```{r echo=TRUE}
samples<-11000

dlfuse_st_results<-DLfuse_st(mcmc_samples = samples,
                             y = y,
                             z = z,
                             sample_size = sample_size,
                             AQS_key = AQS_key,
                             CMAQ_key = CMAQ_key,
                             spatial_dists = spatial_dists, 
                             AQS_unique_total = nrow(spatial_dists),
                             neighbors = neighbors, 
                             CMAQ_unique_total = nrow(neighbors),
                             metrop_var_rho1_trans = (3.00^2),
                             metrop_var_rho2_trans = (3.00^2),
                             metrop_var_A11_trans = (0.40^2),
                             metrop_var_A22_trans = (0.60^2),
                             metrop_var_mu = (0.20^2),
                             metrop_var_mut = rep(0.75^2, times=length(y)),
                             metrop_var_rho3_trans = (3.00^2),
                             metrop_var_alpha = rep(1.40^2, times=nrow(neighbors)),
                             metrop_var_phi0_trans = (0.60^2),
                             metrop_var_phi1_trans = (0.62^2),
                             model_type_indicator = 0)
```

[3]  Comparing parameter estimates to true values:

```{r}
burnin<-1000
thin<-10
keep_set<-seq((burnin + 1), 
              samples, 
              thin)
par(mfrow=c(3,3))

for(j in 1:(d-1)){

   covars_est<-construct_lagged_covars_st(
               z[[j]],
               mean(dlfuse_st_results$lag_info$mu[keep_set]),
               mean(dlfuse_st_results$lag_info$mut[j,keep_set]),
               rowMeans(dlfuse_st_results$lag_info$alpha[,keep_set]),
               sample_size[[j]],
               CMAQ_key[[j]])[[1]]

   plot(covars_true[[j]], 
       covars_est)
   abline(0,1)
   
   }

par(mfrow=c(3,3))
betat<-simplify2array(dlfuse_st_results$betat)[,,keep_set]
for(j in 1:(d-1)){
 
   true<-c(sigma2_epsilon_true,
           (beta0_true + betat_true[j,1] + beta0_tilde_true[AQS_key[[j]]]),
           (beta1_true + betat_true[j,2] + beta1_tilde_true[AQS_key[[j]]]))

   est<-c(mean(dlfuse_st_results$sigma2_epsilon[keep_set]), 
          rowMeans(matrix(dlfuse_st_results$beta0[keep_set], 
                          nrow = sum(sample_size[[j]]), 
                          ncol = length(keep_set), 
                          byrow = TRUE) + 
                   matrix(betat[1,j,], 
                          nrow = sum(sample_size[[j]]), 
                          ncol = length(keep_set), 
                          byrow = TRUE) +
                   matrix(dlfuse_st_results$A11[keep_set],
                          nrow = sum(sample_size[[j]]),
                          ncol = length(keep_set),
                          byrow = TRUE)*dlfuse_st_results$w0[AQS_key[[j]] ,keep_set]),
          rowMeans(matrix(dlfuse_st_results$beta1[keep_set], 
                          nrow = sum(sample_size[[j]]), 
                          ncol = length(keep_set),
                         byrow = TRUE) + 
                   matrix(betat[2,j,], 
                          nrow = sum(sample_size[[j]]), 
                          ncol = length(keep_set), 
                          byrow = TRUE) +
                   matrix(dlfuse_st_results$A21[keep_set],
                          nrow = sum(sample_size[[j]]),
                          ncol = length(keep_set),
                          byrow = TRUE)*dlfuse_st_results$w0[AQS_key[[j]], keep_set] +
                   matrix(dlfuse_st_results$A22[keep_set],
                          nrow = sum(sample_size[[j]]),
                          ncol = length(keep_set),
                          byrow = TRUE)*dlfuse_st_results$w1[AQS_key[[j]], keep_set]))

   plot(est, true)
   abline(0,1)

   }
```

[4]  Spatiotemporal predictions of validation data:

```{r}
spatial_dists_full<-as.matrix(dist(rbind(locs[AQS_key_validation,], locs),
                                   diag = TRUE,
                                   upper = TRUE))
diag(spatial_dists_full)<-0
loc_temp<-rbind(locs[AQS_key_validation,], locs)
for(j in 1:nrow(loc_temp)){
   for(k in 1:nrow(loc_temp)){
      if(prod(loc_temp[j,] == loc_temp[k,]) == 1){
        spatial_dists_full[j,k]<-0
        }
      }
   }

neighbors_full<-1/as.matrix(dist(rbind(grid[CMAQ_key_validation,], grid),
                                 diag = TRUE,
                                 upper = TRUE)) 
diag(neighbors_full)<-0
loc_temp<-rbind(grid[CMAQ_key_validation,], grid)
for(j in 1:nrow(loc_temp)){
   for(k in 1:nrow(loc_temp)){
      if(prod(loc_temp[j,] == loc_temp[k,]) == 1){
        neighbors_full[j,k]<-Inf
        }
      }
   }
diag(neighbors_full)<-0

dlfuse_st_pred_results<-ppd_st(modeling_output = dlfuse_st_results,
                               n_pred = length(y_validation),
                               m_pred = nrow(z_validation),
                               z_pred = z_validation,
                               sample_size_pred = sample_size_validation,
                               spatial_dists_full = spatial_dists_full,  
                               neighbors_full = neighbors_full,  
                               inference_set = keep_set,
                               params_only_indicator = 0,
                               model_type_indicator = 0)
```

[5]  Comparison with other approaches:

```{r}
slr_st_results<-DLfuse_st(mcmc_samples = samples,
                          y = y,
                          z = z,
                          sample_size = sample_size,
                          AQS_key = AQS_key,
                          CMAQ_key = CMAQ_key,
                          spatial_dists = spatial_dists, 
                          AQS_unique_total = nrow(spatial_dists),
                          neighbors = neighbors, 
                          CMAQ_unique_total = nrow(neighbors),
                          metrop_var_rho1_trans = (3.00^2),
                          metrop_var_rho2_trans = (3.00^2),
                          metrop_var_A11_trans = (0.30^2),
                          metrop_var_A22_trans = (0.30^2),
                          metrop_var_mu = (0.10^2),
                          metrop_var_mut = rep(0.75^2, times=length(y)),
                          metrop_var_rho3_trans = (3.00^2),
                          metrop_var_alpha = rep(1.40^2, times=nrow(neighbors)),
                          metrop_var_phi0_trans = (0.60^2),
                          metrop_var_phi1_trans = (0.62^2),
                          model_type_indicator = 3)

slr_st_pred_results<-ppd_st(modeling_output = slr_st_results,
                            n_pred = length(y_validation),
                            m_pred = nrow(z_validation),
                            z_pred = z_validation,
                            sample_size_pred = sample_size_validation,
                            spatial_dists_full = spatial_dists_full,  
                            neighbors_full = neighbors_full,  
                            inference_set = keep_set,
                            params_only_indicator = 0,
                            model_type_indicator = 3)

ok_st_results<-DLfuse_st(mcmc_samples = samples,
                         y = y,
                         z = z,
                         sample_size = sample_size,
                         AQS_key = AQS_key,
                         CMAQ_key = CMAQ_key,
                         spatial_dists = spatial_dists, 
                         AQS_unique_total = nrow(spatial_dists),
                         neighbors = neighbors, 
                         CMAQ_unique_total = nrow(neighbors),
                         metrop_var_rho1_trans = (3.00^2),
                         metrop_var_rho2_trans = (3.00^2),
                         metrop_var_A11_trans = (0.60^2),
                         metrop_var_A22_trans = (0.30^2),
                         metrop_var_mu = (0.10^2),
                         metrop_var_mut = rep(0.75^2, times=length(y)),
                         metrop_var_rho3_trans = (3.00^2),
                         metrop_var_alpha = rep(1.40^2, times=nrow(neighbors)),
                         metrop_var_phi0_trans = (0.60^2),
                         metrop_var_phi1_trans = (0.62^2),
                         model_type_indicator = 2)

ok_st_pred_results<-ppd_st(modeling_output = ok_st_results,
                           n_pred = length(y_validation),
                           m_pred = nrow(z_validation),
                           z_pred = z_validation,
                           sample_size_pred = sample_size_validation,
                           spatial_dists_full = spatial_dists_full,  
                           neighbors_full = neighbors_full,  
                           inference_set = keep_set,
                           params_only_indicator = 0,
                           model_type_indicator = 2)

ds_st_results<-DLfuse_st(mcmc_samples = samples,
                         y = y,
                         z = z,
                         sample_size = sample_size,
                         AQS_key = AQS_key,
                         CMAQ_key = CMAQ_key,
                         spatial_dists = spatial_dists, 
                         AQS_unique_total = nrow(spatial_dists),
                         neighbors = neighbors, 
                         CMAQ_unique_total = nrow(neighbors),
                         metrop_var_rho1_trans = (3.00^2),
                         metrop_var_rho2_trans = (3.00^2),
                         metrop_var_A11_trans = (0.60^2),
                         metrop_var_A22_trans = (0.60^2),
                         metrop_var_mu = (0.10^2),
                         metrop_var_mut = rep(0.75^2, times=length(y)),
                         metrop_var_rho3_trans = (3.00^2),
                         metrop_var_alpha = rep(1.40^2, times=nrow(neighbors)),
                         metrop_var_phi0_trans = (0.60^2),
                         metrop_var_phi1_trans = (0.62^2),
                         model_type_indicator = 1)

ds_st_pred_results<-ppd_st(modeling_output = ds_st_results,
                           n_pred = length(y_validation),
                           m_pred = nrow(z_validation),
                           z_pred = z_validation,
                           sample_size_pred = sample_size_validation,
                           spatial_dists_full = spatial_dists_full,  
                           neighbors_full = neighbors_full,  
                           inference_set = keep_set,
                           params_only_indicator = 0,
                           model_type_indicator = 1)

#Results Matrix
results<-matrix(0,
                nrow = 3,
                ncol = 4)
colnames(results)<-c("dlfuse_st", "slr", "ok", "ds")
rownames(results)<-c("mse", "cover", "length")

#DLfuse_st
cover<-rep(0, 
           times=length(y_validation))
len<-rep(0, 
         times=length(y_validation))
for(j in 1:length(y_validation)){

   ci<-quantile(dlfuse_st_pred_results[[1]][j,], c(0.025, 0.975))
   if((ci[1] <= y_validation[j]) & (ci[2] >= y_validation[j])){
     cover[j]<-1
     }
   len[j]<-ci[2] -
           ci[1]

   }
results[1,1]<-mean((y_validation - 
                   rowMedians(dlfuse_st_pred_results[[1]]))^2)
results[2,1]<-mean(cover)
results[3,1]<-mean(len)

#SLR_st
cover<-rep(0, 
           times=length(y_validation))
len<-rep(0, 
         times=length(y_validation))
for(j in 1:length(y_validation)){

   ci<-quantile(slr_st_pred_results[[1]][j,], c(0.025, 0.975))
   if((ci[1] <= y_validation[j]) & (ci[2] >= y_validation[j])){
     cover[j]<-1
     }
   len[j]<-ci[2] -
           ci[1]

   }
results[1,2]<-mean((y_validation - 
                   rowMedians(slr_st_pred_results[[1]]))^2)
results[2,2]<-mean(cover)
results[3,2]<-mean(len)
      

#OK_st
cover<-rep(0, 
           times=length(y_validation))
len<-rep(0, 
         times=length(y_validation))
for(j in 1:length(y_validation)){

   ci<-quantile(ok_st_pred_results[[1]][j,], c(0.025, 0.975))
   if((ci[1] <= y_validation[j]) & (ci[2] >= y_validation[j])){
     cover[j]<-1
     }
   len[j]<-ci[2] -
           ci[1]

   }
results[1,3]<-mean((y_validation - 
                   rowMedians(ok_st_pred_results[[1]]))^2)
results[2,3]<-mean(cover)
results[3,3]<-mean(len)
     
#DS_st
cover<-rep(0, 
           times=length(y_validation))
len<-rep(0, 
         times=length(y_validation))
for(j in 1:length(y_validation)){

   ci<-quantile(ds_st_pred_results[[1]][j,], c(0.025, 0.975))
   if((ci[1] <= y_validation[j]) & (ci[2] >= y_validation[j])){
     cover[j]<-1
     }
   len[j]<-ci[2] -
           ci[1]

   }
results[1,4]<-mean((y_validation - 
                   rowMedians(ds_st_pred_results[[1]]))^2)
results[2,4]<-mean(cover)
results[3,4]<-mean(len)
    
results
```


