// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// A11_update
Rcpp::List A11_update(arma::vec y, double A11_old, Rcpp::List lagged_covars, double sigma2_epsilon, double beta0, double beta1, double A22_old, double A21_old, arma::vec w0_old, arma::vec w1_old, arma::uvec keep5, arma::vec sample_size, double sigma2_A, double metrop_var_A11_trans, int acctot_A11_trans);
RcppExport SEXP _DLfuse_A11_update(SEXP ySEXP, SEXP A11_oldSEXP, SEXP lagged_covarsSEXP, SEXP sigma2_epsilonSEXP, SEXP beta0SEXP, SEXP beta1SEXP, SEXP A22_oldSEXP, SEXP A21_oldSEXP, SEXP w0_oldSEXP, SEXP w1_oldSEXP, SEXP keep5SEXP, SEXP sample_sizeSEXP, SEXP sigma2_ASEXP, SEXP metrop_var_A11_transSEXP, SEXP acctot_A11_transSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type A11_old(A11_oldSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type lagged_covars(lagged_covarsSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_epsilon(sigma2_epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< double >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< double >::type A22_old(A22_oldSEXP);
    Rcpp::traits::input_parameter< double >::type A21_old(A21_oldSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w0_old(w0_oldSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w1_old(w1_oldSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type keep5(keep5SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sample_size(sample_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_A(sigma2_ASEXP);
    Rcpp::traits::input_parameter< double >::type metrop_var_A11_trans(metrop_var_A11_transSEXP);
    Rcpp::traits::input_parameter< int >::type acctot_A11_trans(acctot_A11_transSEXP);
    rcpp_result_gen = Rcpp::wrap(A11_update(y, A11_old, lagged_covars, sigma2_epsilon, beta0, beta1, A22_old, A21_old, w0_old, w1_old, keep5, sample_size, sigma2_A, metrop_var_A11_trans, acctot_A11_trans));
    return rcpp_result_gen;
END_RCPP
}
// A21_update
double A21_update(arma::vec y, arma::vec mean_temp, Rcpp::List lagged_covars, double sigma2_epsilon, arma::vec w0_old, double sigma2_A);
RcppExport SEXP _DLfuse_A21_update(SEXP ySEXP, SEXP mean_tempSEXP, SEXP lagged_covarsSEXP, SEXP sigma2_epsilonSEXP, SEXP w0_oldSEXP, SEXP sigma2_ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mean_temp(mean_tempSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type lagged_covars(lagged_covarsSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_epsilon(sigma2_epsilonSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w0_old(w0_oldSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_A(sigma2_ASEXP);
    rcpp_result_gen = Rcpp::wrap(A21_update(y, mean_temp, lagged_covars, sigma2_epsilon, w0_old, sigma2_A));
    return rcpp_result_gen;
END_RCPP
}
// A22_update
Rcpp::List A22_update(arma::vec y, double A22_old, Rcpp::List lagged_covars, double sigma2_epsilon, double beta0, double beta1, double A11, double A21_old, arma::vec w0_old, arma::vec w1_old, arma::uvec keep5, arma::vec sample_size, double sigma2_A, double metrop_var_A22_trans, int acctot_A22_trans);
RcppExport SEXP _DLfuse_A22_update(SEXP ySEXP, SEXP A22_oldSEXP, SEXP lagged_covarsSEXP, SEXP sigma2_epsilonSEXP, SEXP beta0SEXP, SEXP beta1SEXP, SEXP A11SEXP, SEXP A21_oldSEXP, SEXP w0_oldSEXP, SEXP w1_oldSEXP, SEXP keep5SEXP, SEXP sample_sizeSEXP, SEXP sigma2_ASEXP, SEXP metrop_var_A22_transSEXP, SEXP acctot_A22_transSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type A22_old(A22_oldSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type lagged_covars(lagged_covarsSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_epsilon(sigma2_epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< double >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< double >::type A11(A11SEXP);
    Rcpp::traits::input_parameter< double >::type A21_old(A21_oldSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w0_old(w0_oldSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w1_old(w1_oldSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type keep5(keep5SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sample_size(sample_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_A(sigma2_ASEXP);
    Rcpp::traits::input_parameter< double >::type metrop_var_A22_trans(metrop_var_A22_transSEXP);
    Rcpp::traits::input_parameter< int >::type acctot_A22_trans(acctot_A22_transSEXP);
    rcpp_result_gen = Rcpp::wrap(A22_update(y, A22_old, lagged_covars, sigma2_epsilon, beta0, beta1, A11, A21_old, w0_old, w1_old, keep5, sample_size, sigma2_A, metrop_var_A22_trans, acctot_A22_trans));
    return rcpp_result_gen;
END_RCPP
}
// DLfuse
Rcpp::List DLfuse(int mcmc_samples, arma::vec y, arma::mat z, arma::vec sample_size, arma::mat spatial_dists, arma::mat neighbors, double metrop_var_A11_trans, double metrop_var_A22_trans, double metrop_var_mu, arma::vec metrop_var_alpha, double metrop_var_phi0_trans, double metrop_var_phi1_trans, Rcpp::Nullable<double> alpha_sigma2_epsilon_prior, Rcpp::Nullable<double> beta_sigma2_epsilon_prior, Rcpp::Nullable<double> sigma2_beta_prior, Rcpp::Nullable<double> sigma2_A_prior, Rcpp::Nullable<double> sigma2_mu_prior, Rcpp::Nullable<double> alpha_tau2_prior, Rcpp::Nullable<double> beta_tau2_prior, Rcpp::Nullable<double> alpha_phi0_prior, Rcpp::Nullable<double> beta_phi0_prior, Rcpp::Nullable<double> alpha_phi1_prior, Rcpp::Nullable<double> beta_phi1_prior, Rcpp::Nullable<double> sigma2_epsilon_init, Rcpp::Nullable<double> beta0_init, Rcpp::Nullable<double> beta1_init, Rcpp::Nullable<double> A11_init, Rcpp::Nullable<double> A22_init, Rcpp::Nullable<double> A21_init, Rcpp::Nullable<double> mu_init, Rcpp::Nullable<Rcpp::NumericVector> alpha_init, Rcpp::Nullable<double> tau2_init, Rcpp::Nullable<Rcpp::NumericVector> w0_init, Rcpp::Nullable<double> phi0_init, Rcpp::Nullable<Rcpp::NumericVector> w1_init, Rcpp::Nullable<double> phi1_init, Rcpp::Nullable<int> collapse_indicator);
RcppExport SEXP _DLfuse_DLfuse(SEXP mcmc_samplesSEXP, SEXP ySEXP, SEXP zSEXP, SEXP sample_sizeSEXP, SEXP spatial_distsSEXP, SEXP neighborsSEXP, SEXP metrop_var_A11_transSEXP, SEXP metrop_var_A22_transSEXP, SEXP metrop_var_muSEXP, SEXP metrop_var_alphaSEXP, SEXP metrop_var_phi0_transSEXP, SEXP metrop_var_phi1_transSEXP, SEXP alpha_sigma2_epsilon_priorSEXP, SEXP beta_sigma2_epsilon_priorSEXP, SEXP sigma2_beta_priorSEXP, SEXP sigma2_A_priorSEXP, SEXP sigma2_mu_priorSEXP, SEXP alpha_tau2_priorSEXP, SEXP beta_tau2_priorSEXP, SEXP alpha_phi0_priorSEXP, SEXP beta_phi0_priorSEXP, SEXP alpha_phi1_priorSEXP, SEXP beta_phi1_priorSEXP, SEXP sigma2_epsilon_initSEXP, SEXP beta0_initSEXP, SEXP beta1_initSEXP, SEXP A11_initSEXP, SEXP A22_initSEXP, SEXP A21_initSEXP, SEXP mu_initSEXP, SEXP alpha_initSEXP, SEXP tau2_initSEXP, SEXP w0_initSEXP, SEXP phi0_initSEXP, SEXP w1_initSEXP, SEXP phi1_initSEXP, SEXP collapse_indicatorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type mcmc_samples(mcmc_samplesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type z(zSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sample_size(sample_sizeSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type spatial_dists(spatial_distsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type neighbors(neighborsSEXP);
    Rcpp::traits::input_parameter< double >::type metrop_var_A11_trans(metrop_var_A11_transSEXP);
    Rcpp::traits::input_parameter< double >::type metrop_var_A22_trans(metrop_var_A22_transSEXP);
    Rcpp::traits::input_parameter< double >::type metrop_var_mu(metrop_var_muSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type metrop_var_alpha(metrop_var_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type metrop_var_phi0_trans(metrop_var_phi0_transSEXP);
    Rcpp::traits::input_parameter< double >::type metrop_var_phi1_trans(metrop_var_phi1_transSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type alpha_sigma2_epsilon_prior(alpha_sigma2_epsilon_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type beta_sigma2_epsilon_prior(beta_sigma2_epsilon_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type sigma2_beta_prior(sigma2_beta_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type sigma2_A_prior(sigma2_A_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type sigma2_mu_prior(sigma2_mu_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type alpha_tau2_prior(alpha_tau2_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type beta_tau2_prior(beta_tau2_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type alpha_phi0_prior(alpha_phi0_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type beta_phi0_prior(beta_phi0_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type alpha_phi1_prior(alpha_phi1_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type beta_phi1_prior(beta_phi1_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type sigma2_epsilon_init(sigma2_epsilon_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type beta0_init(beta0_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type beta1_init(beta1_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type A11_init(A11_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type A22_init(A22_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type A21_init(A21_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type mu_init(mu_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type alpha_init(alpha_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type tau2_init(tau2_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type w0_init(w0_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type phi0_init(phi0_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type w1_init(w1_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type phi1_init(phi1_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type collapse_indicator(collapse_indicatorSEXP);
    rcpp_result_gen = Rcpp::wrap(DLfuse(mcmc_samples, y, z, sample_size, spatial_dists, neighbors, metrop_var_A11_trans, metrop_var_A22_trans, metrop_var_mu, metrop_var_alpha, metrop_var_phi0_trans, metrop_var_phi1_trans, alpha_sigma2_epsilon_prior, beta_sigma2_epsilon_prior, sigma2_beta_prior, sigma2_A_prior, sigma2_mu_prior, alpha_tau2_prior, beta_tau2_prior, alpha_phi0_prior, beta_phi0_prior, alpha_phi1_prior, beta_phi1_prior, sigma2_epsilon_init, beta0_init, beta1_init, A11_init, A22_init, A21_init, mu_init, alpha_init, tau2_init, w0_init, phi0_init, w1_init, phi1_init, collapse_indicator));
    return rcpp_result_gen;
END_RCPP
}
// alpha_update
Rcpp::List alpha_update(arma::vec y, arma::mat z, arma::mat neighbors, arma::vec alpha_old, Rcpp::List lagged_covars, double sigma2_epsilon, double beta0, double beta1, double A11, double A22, double A21, double mu, double tau2_old, arma::vec w0_old, arma::vec w1_old, arma::uvec keep5, arma::vec sample_size, arma::vec metrop_var_alpha, arma::vec acctot_alpha);
RcppExport SEXP _DLfuse_alpha_update(SEXP ySEXP, SEXP zSEXP, SEXP neighborsSEXP, SEXP alpha_oldSEXP, SEXP lagged_covarsSEXP, SEXP sigma2_epsilonSEXP, SEXP beta0SEXP, SEXP beta1SEXP, SEXP A11SEXP, SEXP A22SEXP, SEXP A21SEXP, SEXP muSEXP, SEXP tau2_oldSEXP, SEXP w0_oldSEXP, SEXP w1_oldSEXP, SEXP keep5SEXP, SEXP sample_sizeSEXP, SEXP metrop_var_alphaSEXP, SEXP acctot_alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type z(zSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type neighbors(neighborsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha_old(alpha_oldSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type lagged_covars(lagged_covarsSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_epsilon(sigma2_epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< double >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< double >::type A11(A11SEXP);
    Rcpp::traits::input_parameter< double >::type A22(A22SEXP);
    Rcpp::traits::input_parameter< double >::type A21(A21SEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type tau2_old(tau2_oldSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w0_old(w0_oldSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w1_old(w1_oldSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type keep5(keep5SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sample_size(sample_sizeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type metrop_var_alpha(metrop_var_alphaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type acctot_alpha(acctot_alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(alpha_update(y, z, neighbors, alpha_old, lagged_covars, sigma2_epsilon, beta0, beta1, A11, A22, A21, mu, tau2_old, w0_old, w1_old, keep5, sample_size, metrop_var_alpha, acctot_alpha));
    return rcpp_result_gen;
END_RCPP
}
// beta0_update
double beta0_update(arma::vec y, arma::vec mean_temp, double sigma2_epsilon, arma::vec sample_size, double sigma2_beta);
RcppExport SEXP _DLfuse_beta0_update(SEXP ySEXP, SEXP mean_tempSEXP, SEXP sigma2_epsilonSEXP, SEXP sample_sizeSEXP, SEXP sigma2_betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mean_temp(mean_tempSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_epsilon(sigma2_epsilonSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sample_size(sample_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_beta(sigma2_betaSEXP);
    rcpp_result_gen = Rcpp::wrap(beta0_update(y, mean_temp, sigma2_epsilon, sample_size, sigma2_beta));
    return rcpp_result_gen;
END_RCPP
}
// beta1_update
double beta1_update(arma::vec y, arma::vec mean_temp, Rcpp::List lagged_covars, double sigma2_epsilon, arma::vec sample_size, double sigma2_beta);
RcppExport SEXP _DLfuse_beta1_update(SEXP ySEXP, SEXP mean_tempSEXP, SEXP lagged_covarsSEXP, SEXP sigma2_epsilonSEXP, SEXP sample_sizeSEXP, SEXP sigma2_betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mean_temp(mean_tempSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type lagged_covars(lagged_covarsSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_epsilon(sigma2_epsilonSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sample_size(sample_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_beta(sigma2_betaSEXP);
    rcpp_result_gen = Rcpp::wrap(beta1_update(y, mean_temp, lagged_covars, sigma2_epsilon, sample_size, sigma2_beta));
    return rcpp_result_gen;
END_RCPP
}
// construct_lagged_covars
Rcpp::List construct_lagged_covars(arma::mat z, double mu, arma::vec alpha, arma::vec sample_size);
RcppExport SEXP _DLfuse_construct_lagged_covars(SEXP zSEXP, SEXP muSEXP, SEXP alphaSEXP, SEXP sample_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sample_size(sample_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(construct_lagged_covars(z, mu, alpha, sample_size));
    return rcpp_result_gen;
END_RCPP
}
// construct_mean
arma::vec construct_mean(double beta0, double beta1, double A11, double A22, double A21, arma::vec w0, arma::vec w1, arma::mat Omega, arma::uvec keep, arma::vec sample_size);
RcppExport SEXP _DLfuse_construct_mean(SEXP beta0SEXP, SEXP beta1SEXP, SEXP A11SEXP, SEXP A22SEXP, SEXP A21SEXP, SEXP w0SEXP, SEXP w1SEXP, SEXP OmegaSEXP, SEXP keepSEXP, SEXP sample_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< double >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< double >::type A11(A11SEXP);
    Rcpp::traits::input_parameter< double >::type A22(A22SEXP);
    Rcpp::traits::input_parameter< double >::type A21(A21SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w0(w0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w1(w1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Omega(OmegaSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type keep(keepSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sample_size(sample_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(construct_mean(beta0, beta1, A11, A22, A21, w0, w1, Omega, keep, sample_size));
    return rcpp_result_gen;
END_RCPP
}
// mu_update
Rcpp::List mu_update(arma::vec y, arma::mat z, double mu_old, Rcpp::List lagged_covars, double sigma2_epsilon, double beta0, double beta1, double A11, double A22, double A21, arma::vec alpha_old, arma::vec w0_old, arma::vec w1_old, arma::uvec keep5, arma::vec sample_size, double sigma2_mu, double metrop_var_mu, int acctot_mu);
RcppExport SEXP _DLfuse_mu_update(SEXP ySEXP, SEXP zSEXP, SEXP mu_oldSEXP, SEXP lagged_covarsSEXP, SEXP sigma2_epsilonSEXP, SEXP beta0SEXP, SEXP beta1SEXP, SEXP A11SEXP, SEXP A22SEXP, SEXP A21SEXP, SEXP alpha_oldSEXP, SEXP w0_oldSEXP, SEXP w1_oldSEXP, SEXP keep5SEXP, SEXP sample_sizeSEXP, SEXP sigma2_muSEXP, SEXP metrop_var_muSEXP, SEXP acctot_muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type mu_old(mu_oldSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type lagged_covars(lagged_covarsSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_epsilon(sigma2_epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< double >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< double >::type A11(A11SEXP);
    Rcpp::traits::input_parameter< double >::type A22(A22SEXP);
    Rcpp::traits::input_parameter< double >::type A21(A21SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha_old(alpha_oldSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w0_old(w0_oldSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w1_old(w1_oldSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type keep5(keep5SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sample_size(sample_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_mu(sigma2_muSEXP);
    Rcpp::traits::input_parameter< double >::type metrop_var_mu(metrop_var_muSEXP);
    Rcpp::traits::input_parameter< int >::type acctot_mu(acctot_muSEXP);
    rcpp_result_gen = Rcpp::wrap(mu_update(y, z, mu_old, lagged_covars, sigma2_epsilon, beta0, beta1, A11, A22, A21, alpha_old, w0_old, w1_old, keep5, sample_size, sigma2_mu, metrop_var_mu, acctot_mu));
    return rcpp_result_gen;
END_RCPP
}
// neg_two_loglike_update
double neg_two_loglike_update(arma::vec y, arma::vec mean_temp, double sigma2_epsilon);
RcppExport SEXP _DLfuse_neg_two_loglike_update(SEXP ySEXP, SEXP mean_tempSEXP, SEXP sigma2_epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mean_temp(mean_tempSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_epsilon(sigma2_epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(neg_two_loglike_update(y, mean_temp, sigma2_epsilon));
    return rcpp_result_gen;
END_RCPP
}
// phi_update
Rcpp::List phi_update(double phi_old, arma::mat spatial_dists, arma::vec w, Rcpp::List spatial_corr_info, double alpha_phi, double beta_phi, double metrop_var_phi_trans, int acctot_phi_trans);
RcppExport SEXP _DLfuse_phi_update(SEXP phi_oldSEXP, SEXP spatial_distsSEXP, SEXP wSEXP, SEXP spatial_corr_infoSEXP, SEXP alpha_phiSEXP, SEXP beta_phiSEXP, SEXP metrop_var_phi_transSEXP, SEXP acctot_phi_transSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type phi_old(phi_oldSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type spatial_dists(spatial_distsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type spatial_corr_info(spatial_corr_infoSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_phi(alpha_phiSEXP);
    Rcpp::traits::input_parameter< double >::type beta_phi(beta_phiSEXP);
    Rcpp::traits::input_parameter< double >::type metrop_var_phi_trans(metrop_var_phi_transSEXP);
    Rcpp::traits::input_parameter< int >::type acctot_phi_trans(acctot_phi_transSEXP);
    rcpp_result_gen = Rcpp::wrap(phi_update(phi_old, spatial_dists, w, spatial_corr_info, alpha_phi, beta_phi, metrop_var_phi_trans, acctot_phi_trans));
    return rcpp_result_gen;
END_RCPP
}
// sigma2_epsilon_update
double sigma2_epsilon_update(arma::vec y, arma::vec mean_temp, arma::vec sample_size, double alpha_sigma2_epsilon, double beta_sigma2_epsilon);
RcppExport SEXP _DLfuse_sigma2_epsilon_update(SEXP ySEXP, SEXP mean_tempSEXP, SEXP sample_sizeSEXP, SEXP alpha_sigma2_epsilonSEXP, SEXP beta_sigma2_epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mean_temp(mean_tempSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sample_size(sample_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_sigma2_epsilon(alpha_sigma2_epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type beta_sigma2_epsilon(beta_sigma2_epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(sigma2_epsilon_update(y, mean_temp, sample_size, alpha_sigma2_epsilon, beta_sigma2_epsilon));
    return rcpp_result_gen;
END_RCPP
}
// spatial_corr_fun
Rcpp::List spatial_corr_fun(double phi, arma::mat spatial_dists);
RcppExport SEXP _DLfuse_spatial_corr_fun(SEXP phiSEXP, SEXP spatial_distsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type spatial_dists(spatial_distsSEXP);
    rcpp_result_gen = Rcpp::wrap(spatial_corr_fun(phi, spatial_dists));
    return rcpp_result_gen;
END_RCPP
}
// tau2_update
double tau2_update(int G, arma::mat CAR, arma::vec alpha, double alpha_tau2, double beta_tau2);
RcppExport SEXP _DLfuse_tau2_update(SEXP GSEXP, SEXP CARSEXP, SEXP alphaSEXP, SEXP alpha_tau2SEXP, SEXP beta_tau2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type G(GSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type CAR(CARSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_tau2(alpha_tau2SEXP);
    Rcpp::traits::input_parameter< double >::type beta_tau2(beta_tau2SEXP);
    rcpp_result_gen = Rcpp::wrap(tau2_update(G, CAR, alpha, alpha_tau2, beta_tau2));
    return rcpp_result_gen;
END_RCPP
}
// w0_update
arma::vec w0_update(arma::vec y, arma::vec mean_temp, Rcpp::List lagged_covars, double sigma2_epsilon, double A11, double A21, arma::mat Sigma0_inv);
RcppExport SEXP _DLfuse_w0_update(SEXP ySEXP, SEXP mean_tempSEXP, SEXP lagged_covarsSEXP, SEXP sigma2_epsilonSEXP, SEXP A11SEXP, SEXP A21SEXP, SEXP Sigma0_invSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mean_temp(mean_tempSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type lagged_covars(lagged_covarsSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_epsilon(sigma2_epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type A11(A11SEXP);
    Rcpp::traits::input_parameter< double >::type A21(A21SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma0_inv(Sigma0_invSEXP);
    rcpp_result_gen = Rcpp::wrap(w0_update(y, mean_temp, lagged_covars, sigma2_epsilon, A11, A21, Sigma0_inv));
    return rcpp_result_gen;
END_RCPP
}
// w1_update
arma::vec w1_update(arma::vec y, arma::vec mean_temp, Rcpp::List lagged_covars, double sigma2_epsilon, double A22, arma::mat Sigma1_inv);
RcppExport SEXP _DLfuse_w1_update(SEXP ySEXP, SEXP mean_tempSEXP, SEXP lagged_covarsSEXP, SEXP sigma2_epsilonSEXP, SEXP A22SEXP, SEXP Sigma1_invSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mean_temp(mean_tempSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type lagged_covars(lagged_covarsSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_epsilon(sigma2_epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type A22(A22SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma1_inv(Sigma1_invSEXP);
    rcpp_result_gen = Rcpp::wrap(w1_update(y, mean_temp, lagged_covars, sigma2_epsilon, A22, Sigma1_inv));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DLfuse_A11_update", (DL_FUNC) &_DLfuse_A11_update, 15},
    {"_DLfuse_A21_update", (DL_FUNC) &_DLfuse_A21_update, 6},
    {"_DLfuse_A22_update", (DL_FUNC) &_DLfuse_A22_update, 15},
    {"_DLfuse_DLfuse", (DL_FUNC) &_DLfuse_DLfuse, 37},
    {"_DLfuse_alpha_update", (DL_FUNC) &_DLfuse_alpha_update, 19},
    {"_DLfuse_beta0_update", (DL_FUNC) &_DLfuse_beta0_update, 5},
    {"_DLfuse_beta1_update", (DL_FUNC) &_DLfuse_beta1_update, 6},
    {"_DLfuse_construct_lagged_covars", (DL_FUNC) &_DLfuse_construct_lagged_covars, 4},
    {"_DLfuse_construct_mean", (DL_FUNC) &_DLfuse_construct_mean, 10},
    {"_DLfuse_mu_update", (DL_FUNC) &_DLfuse_mu_update, 18},
    {"_DLfuse_neg_two_loglike_update", (DL_FUNC) &_DLfuse_neg_two_loglike_update, 3},
    {"_DLfuse_phi_update", (DL_FUNC) &_DLfuse_phi_update, 8},
    {"_DLfuse_sigma2_epsilon_update", (DL_FUNC) &_DLfuse_sigma2_epsilon_update, 5},
    {"_DLfuse_spatial_corr_fun", (DL_FUNC) &_DLfuse_spatial_corr_fun, 2},
    {"_DLfuse_tau2_update", (DL_FUNC) &_DLfuse_tau2_update, 5},
    {"_DLfuse_w0_update", (DL_FUNC) &_DLfuse_w0_update, 7},
    {"_DLfuse_w1_update", (DL_FUNC) &_DLfuse_w1_update, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_DLfuse(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
