# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

A11_update <- function(y, A11_old, lagged_covars, sigma2_epsilon, beta0, beta1, A22_old, A21_old, w0_old, w1_old, keep5, sample_size, sigma2_A, metrop_var_A11_trans, acctot_A11_trans) {
    .Call(`_DLfuse_A11_update`, y, A11_old, lagged_covars, sigma2_epsilon, beta0, beta1, A22_old, A21_old, w0_old, w1_old, keep5, sample_size, sigma2_A, metrop_var_A11_trans, acctot_A11_trans)
}

A21_update <- function(y, mean_temp, lagged_covars, sigma2_epsilon, w0_old, sigma2_A) {
    .Call(`_DLfuse_A21_update`, y, mean_temp, lagged_covars, sigma2_epsilon, w0_old, sigma2_A)
}

A22_update <- function(y, A22_old, lagged_covars, sigma2_epsilon, beta0, beta1, A11, A21_old, w0_old, w1_old, keep5, sample_size, sigma2_A, metrop_var_A22_trans, acctot_A22_trans) {
    .Call(`_DLfuse_A22_update`, y, A22_old, lagged_covars, sigma2_epsilon, beta0, beta1, A11, A21_old, w0_old, w1_old, keep5, sample_size, sigma2_A, metrop_var_A22_trans, acctot_A22_trans)
}

DLfuse <- function(mcmc_samples, y, z, sample_size, spatial_dists, neighbors, metrop_var_A11_trans, metrop_var_A22_trans, metrop_var_mu, metrop_var_alpha, metrop_var_phi0_trans, metrop_var_phi1_trans, alpha_sigma2_epsilon_prior = NULL, beta_sigma2_epsilon_prior = NULL, sigma2_beta_prior = NULL, sigma2_A_prior = NULL, sigma2_mu_prior = NULL, alpha_tau2_prior = NULL, beta_tau2_prior = NULL, alpha_phi0_prior = NULL, beta_phi0_prior = NULL, alpha_phi1_prior = NULL, beta_phi1_prior = NULL, sigma2_epsilon_init = NULL, beta0_init = NULL, beta1_init = NULL, A11_init = NULL, A22_init = NULL, A21_init = NULL, mu_init = NULL, alpha_init = NULL, tau2_init = NULL, w0_init = NULL, phi0_init = NULL, w1_init = NULL, phi1_init = NULL, collapse_indicator = NULL) {
    .Call(`_DLfuse_DLfuse`, mcmc_samples, y, z, sample_size, spatial_dists, neighbors, metrop_var_A11_trans, metrop_var_A22_trans, metrop_var_mu, metrop_var_alpha, metrop_var_phi0_trans, metrop_var_phi1_trans, alpha_sigma2_epsilon_prior, beta_sigma2_epsilon_prior, sigma2_beta_prior, sigma2_A_prior, sigma2_mu_prior, alpha_tau2_prior, beta_tau2_prior, alpha_phi0_prior, beta_phi0_prior, alpha_phi1_prior, beta_phi1_prior, sigma2_epsilon_init, beta0_init, beta1_init, A11_init, A22_init, A21_init, mu_init, alpha_init, tau2_init, w0_init, phi0_init, w1_init, phi1_init, collapse_indicator)
}

alpha_update <- function(y, z, neighbors, alpha_old, lagged_covars, sigma2_epsilon, beta0, beta1, A11, A22, A21, mu, tau2_old, w0_old, w1_old, keep5, sample_size, metrop_var_alpha, acctot_alpha) {
    .Call(`_DLfuse_alpha_update`, y, z, neighbors, alpha_old, lagged_covars, sigma2_epsilon, beta0, beta1, A11, A22, A21, mu, tau2_old, w0_old, w1_old, keep5, sample_size, metrop_var_alpha, acctot_alpha)
}

beta0_update <- function(y, mean_temp, sigma2_epsilon, sample_size, sigma2_beta) {
    .Call(`_DLfuse_beta0_update`, y, mean_temp, sigma2_epsilon, sample_size, sigma2_beta)
}

beta1_update <- function(y, mean_temp, lagged_covars, sigma2_epsilon, sample_size, sigma2_beta) {
    .Call(`_DLfuse_beta1_update`, y, mean_temp, lagged_covars, sigma2_epsilon, sample_size, sigma2_beta)
}

construct_lagged_covars <- function(z, mu, alpha, sample_size) {
    .Call(`_DLfuse_construct_lagged_covars`, z, mu, alpha, sample_size)
}

construct_mean <- function(beta0, beta1, A11, A22, A21, w0, w1, Omega, keep, sample_size) {
    .Call(`_DLfuse_construct_mean`, beta0, beta1, A11, A22, A21, w0, w1, Omega, keep, sample_size)
}

mu_update <- function(y, z, mu_old, lagged_covars, sigma2_epsilon, beta0, beta1, A11, A22, A21, alpha_old, w0_old, w1_old, keep5, sample_size, sigma2_mu, metrop_var_mu, acctot_mu) {
    .Call(`_DLfuse_mu_update`, y, z, mu_old, lagged_covars, sigma2_epsilon, beta0, beta1, A11, A22, A21, alpha_old, w0_old, w1_old, keep5, sample_size, sigma2_mu, metrop_var_mu, acctot_mu)
}

neg_two_loglike_update <- function(y, mean_temp, sigma2_epsilon) {
    .Call(`_DLfuse_neg_two_loglike_update`, y, mean_temp, sigma2_epsilon)
}

phi_update <- function(phi_old, spatial_dists, w, spatial_corr_info, alpha_phi, beta_phi, metrop_var_phi_trans, acctot_phi_trans) {
    .Call(`_DLfuse_phi_update`, phi_old, spatial_dists, w, spatial_corr_info, alpha_phi, beta_phi, metrop_var_phi_trans, acctot_phi_trans)
}

sigma2_epsilon_update <- function(y, mean_temp, sample_size, alpha_sigma2_epsilon, beta_sigma2_epsilon) {
    .Call(`_DLfuse_sigma2_epsilon_update`, y, mean_temp, sample_size, alpha_sigma2_epsilon, beta_sigma2_epsilon)
}

spatial_corr_fun <- function(phi, spatial_dists) {
    .Call(`_DLfuse_spatial_corr_fun`, phi, spatial_dists)
}

tau2_update <- function(G, CAR, alpha, alpha_tau2, beta_tau2) {
    .Call(`_DLfuse_tau2_update`, G, CAR, alpha, alpha_tau2, beta_tau2)
}

w0_update <- function(y, mean_temp, lagged_covars, sigma2_epsilon, A11, A21, Sigma0_inv) {
    .Call(`_DLfuse_w0_update`, y, mean_temp, lagged_covars, sigma2_epsilon, A11, A21, Sigma0_inv)
}

w1_update <- function(y, mean_temp, lagged_covars, sigma2_epsilon, A22, Sigma1_inv) {
    .Call(`_DLfuse_w1_update`, y, mean_temp, lagged_covars, sigma2_epsilon, A22, Sigma1_inv)
}

