# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

A11_update_s <- function(y, A11_old, lagged_covars, sigma2_epsilon, beta0, beta1, A22_old, A21_old, w0_old, w1_old, keep5, sample_size, sigma2_A, metrop_var_A11_trans, acctot_A11_trans) {
    .Call(`_DLfuse_A11_update_s`, y, A11_old, lagged_covars, sigma2_epsilon, beta0, beta1, A22_old, A21_old, w0_old, w1_old, keep5, sample_size, sigma2_A, metrop_var_A11_trans, acctot_A11_trans)
}

A11_update_st <- function(y, AQS_key_mat, A11_old, lagged_covars, sigma2_epsilon, beta0, beta1, betat, A22_old, A21_old, w0_old, w1_old, keep7, sample_size, sigma2_A, metrop_var_A11_trans, acctot_A11_trans) {
    .Call(`_DLfuse_A11_update_st`, y, AQS_key_mat, A11_old, lagged_covars, sigma2_epsilon, beta0, beta1, betat, A22_old, A21_old, w0_old, w1_old, keep7, sample_size, sigma2_A, metrop_var_A11_trans, acctot_A11_trans)
}

A21_update_s <- function(y, mean_temp, lagged_covars, sigma2_epsilon, w0_old, sigma2_A) {
    .Call(`_DLfuse_A21_update_s`, y, mean_temp, lagged_covars, sigma2_epsilon, w0_old, sigma2_A)
}

A21_update_st <- function(y, AQS_key_mat, mean_temp, lagged_covars, sigma2_epsilon, w0_old, sigma2_A) {
    .Call(`_DLfuse_A21_update_st`, y, AQS_key_mat, mean_temp, lagged_covars, sigma2_epsilon, w0_old, sigma2_A)
}

A22_update_s <- function(y, A22_old, lagged_covars, sigma2_epsilon, beta0, beta1, A11, A21_old, w0_old, w1_old, keep5, sample_size, sigma2_A, metrop_var_A22_trans, acctot_A22_trans) {
    .Call(`_DLfuse_A22_update_s`, y, A22_old, lagged_covars, sigma2_epsilon, beta0, beta1, A11, A21_old, w0_old, w1_old, keep5, sample_size, sigma2_A, metrop_var_A22_trans, acctot_A22_trans)
}

A22_update_st <- function(y, AQS_key_mat, A22_old, lagged_covars, sigma2_epsilon, beta0, beta1, betat, A11, A21_old, w0_old, w1_old, keep7, sample_size, sigma2_A, metrop_var_A22_trans, acctot_A22_trans) {
    .Call(`_DLfuse_A22_update_st`, y, AQS_key_mat, A22_old, lagged_covars, sigma2_epsilon, beta0, beta1, betat, A11, A21_old, w0_old, w1_old, keep7, sample_size, sigma2_A, metrop_var_A22_trans, acctot_A22_trans)
}

DLfuse_s <- function(mcmc_samples, y, z, sample_size, spatial_dists, neighbors, metrop_var_A11_trans, metrop_var_A22_trans, metrop_var_mu, metrop_var_alpha, metrop_var_phi0_trans, metrop_var_phi1_trans, alpha_sigma2_epsilon_prior = NULL, beta_sigma2_epsilon_prior = NULL, sigma2_beta_prior = NULL, sigma2_A_prior = NULL, sigma2_mu_prior = NULL, alpha_tau2_prior = NULL, beta_tau2_prior = NULL, alpha_phi0_prior = NULL, beta_phi0_prior = NULL, alpha_phi1_prior = NULL, beta_phi1_prior = NULL, sigma2_epsilon_init = NULL, beta0_init = NULL, beta1_init = NULL, A11_init = NULL, A22_init = NULL, A21_init = NULL, mu_init = NULL, alpha_init = NULL, tau2_init = NULL, w0_init = NULL, phi0_init = NULL, w1_init = NULL, phi1_init = NULL, model_type_indicator = NULL) {
    .Call(`_DLfuse_DLfuse_s`, mcmc_samples, y, z, sample_size, spatial_dists, neighbors, metrop_var_A11_trans, metrop_var_A22_trans, metrop_var_mu, metrop_var_alpha, metrop_var_phi0_trans, metrop_var_phi1_trans, alpha_sigma2_epsilon_prior, beta_sigma2_epsilon_prior, sigma2_beta_prior, sigma2_A_prior, sigma2_mu_prior, alpha_tau2_prior, beta_tau2_prior, alpha_phi0_prior, beta_phi0_prior, alpha_phi1_prior, beta_phi1_prior, sigma2_epsilon_init, beta0_init, beta1_init, A11_init, A22_init, A21_init, mu_init, alpha_init, tau2_init, w0_init, phi0_init, w1_init, phi1_init, model_type_indicator)
}

DLfuse_st <- function(mcmc_samples, y, z, sample_size, AQS_key, CMAQ_key, spatial_dists, AQS_unique_total, neighbors, CMAQ_unique_total, metrop_var_rho1_trans, metrop_var_rho2_trans, metrop_var_A11_trans, metrop_var_A22_trans, metrop_var_mu, metrop_var_mut, metrop_var_rho3_trans, metrop_var_alpha, metrop_var_phi0_trans, metrop_var_phi1_trans, alpha_sigma2_epsilon_prior = NULL, beta_sigma2_epsilon_prior = NULL, sigma2_beta_prior = NULL, Omega_V_inv_prior = NULL, nu_V_inv_prior = NULL, a_rho1_prior = NULL, b_rho1_prior = NULL, a_rho2_prior = NULL, b_rho2_prior = NULL, sigma2_A_prior = NULL, sigma2_mu_prior = NULL, alpha_sigma2_delta_prior = NULL, beta_sigma2_delta_prior = NULL, a_rho3_prior = NULL, b_rho3_prior = NULL, alpha_tau2_prior = NULL, beta_tau2_prior = NULL, alpha_phi0_prior = NULL, beta_phi0_prior = NULL, alpha_phi1_prior = NULL, beta_phi1_prior = NULL, sigma2_epsilon_init = NULL, beta0_init = NULL, beta1_init = NULL, betat_init = NULL, V_init = NULL, rho1_init = NULL, rho2_init = NULL, A11_init = NULL, A22_init = NULL, A21_init = NULL, mu_init = NULL, mut_init = NULL, sigma2_delta_init = NULL, rho3_init = NULL, alpha_init = NULL, tau2_init = NULL, w0_init = NULL, phi0_init = NULL, w1_init = NULL, phi1_init = NULL, model_type_indicator = NULL) {
    .Call(`_DLfuse_DLfuse_st`, mcmc_samples, y, z, sample_size, AQS_key, CMAQ_key, spatial_dists, AQS_unique_total, neighbors, CMAQ_unique_total, metrop_var_rho1_trans, metrop_var_rho2_trans, metrop_var_A11_trans, metrop_var_A22_trans, metrop_var_mu, metrop_var_mut, metrop_var_rho3_trans, metrop_var_alpha, metrop_var_phi0_trans, metrop_var_phi1_trans, alpha_sigma2_epsilon_prior, beta_sigma2_epsilon_prior, sigma2_beta_prior, Omega_V_inv_prior, nu_V_inv_prior, a_rho1_prior, b_rho1_prior, a_rho2_prior, b_rho2_prior, sigma2_A_prior, sigma2_mu_prior, alpha_sigma2_delta_prior, beta_sigma2_delta_prior, a_rho3_prior, b_rho3_prior, alpha_tau2_prior, beta_tau2_prior, alpha_phi0_prior, beta_phi0_prior, alpha_phi1_prior, beta_phi1_prior, sigma2_epsilon_init, beta0_init, beta1_init, betat_init, V_init, rho1_init, rho2_init, A11_init, A22_init, A21_init, mu_init, mut_init, sigma2_delta_init, rho3_init, alpha_init, tau2_init, w0_init, phi0_init, w1_init, phi1_init, model_type_indicator)
}

V_update_st <- function(betat, rho1_old, rho2_old, Omega_V_inv, nu_v_inv) {
    .Call(`_DLfuse_V_update_st`, betat, rho1_old, rho2_old, Omega_V_inv, nu_v_inv)
}

alpha_update_s <- function(y, z, neighbors, alpha_old, lagged_covars, sigma2_epsilon, beta0, beta1, A11, A22, A21, mu, tau2_old, w0_old, w1_old, keep5, sample_size, metrop_var_alpha, acctot_alpha) {
    .Call(`_DLfuse_alpha_update_s`, y, z, neighbors, alpha_old, lagged_covars, sigma2_epsilon, beta0, beta1, A11, A22, A21, mu, tau2_old, w0_old, w1_old, keep5, sample_size, metrop_var_alpha, acctot_alpha)
}

alpha_update_st <- function(y, z, neighbors, alpha_old, lagged_covars, sigma2_epsilon, beta0, beta1, betat, A11, A22, A21, mu, mut, tau2_old, w0_old, w1_old, keep7, sample_size, AQS_key, CMAQ_key, metrop_var_alpha, acctot_alpha) {
    .Call(`_DLfuse_alpha_update_st`, y, z, neighbors, alpha_old, lagged_covars, sigma2_epsilon, beta0, beta1, betat, A11, A22, A21, mu, mut, tau2_old, w0_old, w1_old, keep7, sample_size, AQS_key, CMAQ_key, metrop_var_alpha, acctot_alpha)
}

beta0_update_s <- function(y, mean_temp, sigma2_epsilon, sample_size, sigma2_beta) {
    .Call(`_DLfuse_beta0_update_s`, y, mean_temp, sigma2_epsilon, sample_size, sigma2_beta)
}

beta0_update_st <- function(y, mean_temp, sigma2_epsilon, sigma2_beta) {
    .Call(`_DLfuse_beta0_update_st`, y, mean_temp, sigma2_epsilon, sigma2_beta)
}

beta1_update_s <- function(y, mean_temp, lagged_covars, sigma2_epsilon, sample_size, sigma2_beta) {
    .Call(`_DLfuse_beta1_update_s`, y, mean_temp, lagged_covars, sigma2_epsilon, sample_size, sigma2_beta)
}

beta1_update_st <- function(y, mean_temp, lagged_covars, sigma2_epsilon, sample_size, sigma2_beta) {
    .Call(`_DLfuse_beta1_update_st`, y, mean_temp, lagged_covars, sigma2_epsilon, sample_size, sigma2_beta)
}

betat_update_st <- function(y_t, mean_temp_t, lagged_covars_t, sigma2_epsilon, betat_previous, V_old, rho1_old, rho2_old) {
    .Call(`_DLfuse_betat_update_st`, y_t, mean_temp_t, lagged_covars_t, sigma2_epsilon, betat_previous, V_old, rho1_old, rho2_old)
}

construct_lagged_covars_s <- function(z, mu, alpha, sample_size) {
    .Call(`_DLfuse_construct_lagged_covars_s`, z, mu, alpha, sample_size)
}

construct_lagged_covars_st <- function(z_t, mu, mut_t, alpha, sample_size_t, CMAQ_key) {
    .Call(`_DLfuse_construct_lagged_covars_st`, z_t, mu, mut_t, alpha, sample_size_t, CMAQ_key)
}

construct_mean_s <- function(beta0, beta1, A11, A22, A21, w0, w1, Omega, keep, sample_size) {
    .Call(`_DLfuse_construct_mean_s`, beta0, beta1, A11, A22, A21, w0, w1, Omega, keep, sample_size)
}

construct_mean_st <- function(beta0, beta1, betat_t, A11, A22, A21, w0, w1, Omega_t, keep, sample_size_t, AQS_key_mat_t) {
    .Call(`_DLfuse_construct_mean_st`, beta0, beta1, betat_t, A11, A22, A21, w0, w1, Omega_t, keep, sample_size_t, AQS_key_mat_t)
}

mu_update_s <- function(y, z, mu_old, lagged_covars, sigma2_epsilon, beta0, beta1, A11, A22, A21, alpha_old, w0_old, w1_old, keep5, sample_size, sigma2_mu, metrop_var_mu, acctot_mu) {
    .Call(`_DLfuse_mu_update_s`, y, z, mu_old, lagged_covars, sigma2_epsilon, beta0, beta1, A11, A22, A21, alpha_old, w0_old, w1_old, keep5, sample_size, sigma2_mu, metrop_var_mu, acctot_mu)
}

mu_update_st <- function(y, z, mu_old, lagged_covars, sigma2_epsilon, beta0, beta1, betat, A11, A22, A21, mut_old, alpha_old, w0_old, w1_old, keep7, sample_size, AQS_key_mat, CMAQ_key, sigma2_mu, metrop_var_mu, acctot_mu) {
    .Call(`_DLfuse_mu_update_st`, y, z, mu_old, lagged_covars, sigma2_epsilon, beta0, beta1, betat, A11, A22, A21, mut_old, alpha_old, w0_old, w1_old, keep7, sample_size, AQS_key_mat, CMAQ_key, sigma2_mu, metrop_var_mu, acctot_mu)
}

mut_update_st <- function(y_t, z_t, mut_t_old, lagged_covars_t, sigma2_epsilon, beta0, beta1, betat_t, A11, A22, A21, mu, mut_previous, sigma2_delta_old, rho3_old, alpha_old, w0_old, w1_old, keep7, sample_size_t, AQS_key_mat_t, CMAQ_key_t, metrop_var_mut_t, acctot_mut_t) {
    .Call(`_DLfuse_mut_update_st`, y_t, z_t, mut_t_old, lagged_covars_t, sigma2_epsilon, beta0, beta1, betat_t, A11, A22, A21, mu, mut_previous, sigma2_delta_old, rho3_old, alpha_old, w0_old, w1_old, keep7, sample_size_t, AQS_key_mat_t, CMAQ_key_t, metrop_var_mut_t, acctot_mut_t)
}

neg_two_loglike_update_s <- function(y, mean_temp, sigma2_epsilon) {
    .Call(`_DLfuse_neg_two_loglike_update_s`, y, mean_temp, sigma2_epsilon)
}

neg_two_loglike_update_st <- function(y, mean_temp, sigma2_epsilon) {
    .Call(`_DLfuse_neg_two_loglike_update_st`, y, mean_temp, sigma2_epsilon)
}

phi_update <- function(phi_old, spatial_dists, w, spatial_corr_info, alpha_phi, beta_phi, metrop_var_phi_trans, acctot_phi_trans) {
    .Call(`_DLfuse_phi_update`, phi_old, spatial_dists, w, spatial_corr_info, alpha_phi, beta_phi, metrop_var_phi_trans, acctot_phi_trans)
}

ppd_s <- function(modeling_output, n_pred, m_pred, z_pred, sample_size_pred, spatial_dists_full, neighbors_full, inference_set, params_only_indicator = NULL, model_type_indicator = NULL) {
    .Call(`_DLfuse_ppd_s`, modeling_output, n_pred, m_pred, z_pred, sample_size_pred, spatial_dists_full, neighbors_full, inference_set, params_only_indicator, model_type_indicator)
}

rho1_update_st <- function(rho1_old, betat, V, rho2_old, a_rho1, b_rho1, metrop_var_rho1_trans, acctot_rho1_trans) {
    .Call(`_DLfuse_rho1_update_st`, rho1_old, betat, V, rho2_old, a_rho1, b_rho1, metrop_var_rho1_trans, acctot_rho1_trans)
}

rho2_update_st <- function(rho2_old, betat, V, rho1, a_rho2, b_rho2, metrop_var_rho2_trans, acctot_rho2_trans) {
    .Call(`_DLfuse_rho2_update_st`, rho2_old, betat, V, rho1, a_rho2, b_rho2, metrop_var_rho2_trans, acctot_rho2_trans)
}

rho3_update_st <- function(rho3_old, mut, sigma2_delta, a_rho3, b_rho3, metrop_var_rho3_trans, acctot_rho3_trans) {
    .Call(`_DLfuse_rho3_update_st`, rho3_old, mut, sigma2_delta, a_rho3, b_rho3, metrop_var_rho3_trans, acctot_rho3_trans)
}

sigma2_delta_update_st <- function(mut, rho3_old, alpha_sigma2_delta, beta_sigma2_delta) {
    .Call(`_DLfuse_sigma2_delta_update_st`, mut, rho3_old, alpha_sigma2_delta, beta_sigma2_delta)
}

sigma2_epsilon_update_s <- function(y, mean_temp, sample_size, alpha_sigma2_epsilon, beta_sigma2_epsilon) {
    .Call(`_DLfuse_sigma2_epsilon_update_s`, y, mean_temp, sample_size, alpha_sigma2_epsilon, beta_sigma2_epsilon)
}

sigma2_epsilon_update_st <- function(y, mean_temp, alpha_sigma2_epsilon, beta_sigma2_epsilon) {
    .Call(`_DLfuse_sigma2_epsilon_update_st`, y, mean_temp, alpha_sigma2_epsilon, beta_sigma2_epsilon)
}

spatial_corr_fun <- function(phi, spatial_dists) {
    .Call(`_DLfuse_spatial_corr_fun`, phi, spatial_dists)
}

tau2_update <- function(G, CAR, alpha, alpha_tau2, beta_tau2) {
    .Call(`_DLfuse_tau2_update`, G, CAR, alpha, alpha_tau2, beta_tau2)
}

w0_update_s <- function(y, mean_temp, lagged_covars, sigma2_epsilon, A11, A21, Sigma0_inv) {
    .Call(`_DLfuse_w0_update_s`, y, mean_temp, lagged_covars, sigma2_epsilon, A11, A21, Sigma0_inv)
}

w0_update_st <- function(y, AQS_key_mat, mean_temp, lagged_covars, sigma2_epsilon, A11, A21, Sigma0_inv) {
    .Call(`_DLfuse_w0_update_st`, y, AQS_key_mat, mean_temp, lagged_covars, sigma2_epsilon, A11, A21, Sigma0_inv)
}

w1_update_s <- function(y, mean_temp, lagged_covars, sigma2_epsilon, A22, Sigma1_inv) {
    .Call(`_DLfuse_w1_update_s`, y, mean_temp, lagged_covars, sigma2_epsilon, A22, Sigma1_inv)
}

w1_update_st <- function(y, AQS_key_mat, mean_temp, lagged_covars, sigma2_epsilon, A22, Sigma1_inv) {
    .Call(`_DLfuse_w1_update_st`, y, AQS_key_mat, mean_temp, lagged_covars, sigma2_epsilon, A22, Sigma1_inv)
}

